In [1]:
import pandas as pd

In [ ]:
file = "../data.csv"
data = pd.read_csv("data.csv")

In [9]:
data.tail()

,timestamp,aimp,amud,arnd,asin1,asin2,adbr,adfl,bed1,bed2,bfo1,bfo2,bso1,bso2,bso3,ced1,cfo1,cso1,y,category
4999995,2023-02-27 20:53:15,0.0,-15.0,19.146985,-0.506452,0.826317,0.0,0.0,1.679129,0.573972,0.600126,46.743277,-14.161588,0.101711,0.444078,404.386243,-11.330682,34.392976,0.0,0.0
4999996,2023-02-27 20:53:16,0.0,-15.0,18.995890,-0.506435,0.826429,0.0,0.0,1.662337,0.545274,0.588243,46.616762,-14.161774,0.149931,0.443609,404.997544,-11.303570,34.271856,0.0,0.0
4999997,2023-02-27 20:53:17,0.0,-15.0,19.034410,-0.506417,0.826542,0.0,0.0,1.645714,0.518010,0.576595,46.490556,-14.161971,0.194793,0.443141,405.567265,-11.277001,34.150435,0.0,0.0
4999998,2023-02-27 20:53:18,0.0,-15.0,19.168969,-0.506400,0.826655,0.0,0.0,1.629257,0.492110,0.565177,46.364658,-14.162178,0.235987,0.442674,406.098996,-11.250965,34.028822,0.0,0.0
4999999,2023-02-27 20:53:19,0.0,-15.0,19.309191,-0.506383,0.826767,0.0,0.0,1.612964,0.467504,0.553986,46.239067,-14.162395,0.273255,0.442206,406.595841,-11.225456,33.907112,0.0,0.0

In [ ]:
data[data['category'] == 1]

timestamp    4809900
aimp         4809900
amud         4809900
arnd         4809900
asin1        4809900
asin2        4809900
adbr         4809900
adfl         4809900
bed1         4809900
bed2         4809900
bfo1         4809900
bfo2         4809900
bso1         4809900
bso2         4809900
bso3         4809900
ced1         4809900
cfo1         4809900
cso1         4809900
y            4809900
category     4809900
dtype: int64

In [13]:
data.isna().sum()

timestamp    0
aimp         0
amud         0
arnd         0
asin1        0
asin2        0
adbr         0
adfl         0
bed1         0
bed2         0
bfo1         0
bfo2         0
bso1         0
bso2         0
bso3         0
ced1         0
cfo1         0
cso1         0
y            0
category     0
dtype: int64

In [14]:
print("NaN per column:\n", data.isna().sum())
print("\nDuplicate rows:", data.duplicated().sum())

NaN per column:
 timestamp    0
aimp         0
amud         0
arnd         0
asin1        0
asin2        0
adbr         0
adfl         0
bed1         0
bed2         0
bfo1         0
bfo2         0
bso1         0
bso2         0
bso3         0
ced1         0
cfo1         0
cso1         0
y            0
category     0
dtype: int64

Duplicate rows: 0

In [1]:
import torch

In [7]:
y = torch.full((5, 5), 1).nonzero().t().contiguous()
print(y)
print(y.shape)

tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
         4],
        [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
         4]])
torch.Size([2, 25])

In [14]:
a = (torch.arange(0,5).repeat(2).reshape(2, 5, 1).expand((2, 5, 25)).reshape(2, -1) * 10)

print(a)
print(a.shape)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20,
         20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
         20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
         30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40,
         40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20,
         20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
         20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
         30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40,
         40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]])
torch.Size([2, 125])

In [2]:
import pandas as pd

train_df = pd.read_csv("./projects/Source/datasets/train.csv")
test_df = pd.read_csv("./projects/Source/datasets/test.csv")

FileNotFoundError: [Errno 2] No such file or directory: './projects/Source/datasets/train.csv'

In [20]:
test_df[test_df['label'] == 1].count()

aimp     19000
amud     19000
arnd     19000
asin1    19000
asin2    19000
adbr     19000
adfl     19000
bed1     19000
bed2     19000
bfo1     19000
bfo2     19000
bso1     19000
bso2     19000
bso3     19000
ced1     19000
cfo1     19000
cso1     19000
label    19000
dtype: int64

In [19]:
train_df.head()

,aimp,amud,arnd,asin1,asin2,adbr,adfl,bed1,bed2,bfo1,bfo2,bso1,bso2,bso3,ced1,cfo1,cso1,label
0,0.0,1.0,20.000000,0.00000,0.0000,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
1,0.0,1.0,20.080031,0.00002,0.0002,0.0,0.0,0.0,0.0,0.0,4.993912e-07,0.000789,0.0,0.0,0.0,0.000021,0.001229,0.0
2,0.0,1.0,20.276562,0.00004,0.0004,0.0,0.0,0.0,0.0,0.0,1.496957e-06,0.003115,0.0,0.0,0.0,0.000104,0.004833,0.0
3,0.0,1.0,20.730938,0.00006,0.0006,0.0,0.0,0.0,0.0,0.0,2.991484e-06,0.006914,0.0,0.0,0.0,0.000285,0.010688,0.0
4,0.0,1.0,21.118101,0.00008,0.0008,0.0,0.0,0.0,0.0,0.0,4.981761e-06,0.012123,0.0,0.0,0.0,0.000601,0.018669,0.0

In [6]:
import pandas as pd

df = pd.read_csv("./Desktop/projects/Source/datasets/SWaT/swat_train2.csv")

df.head()

,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,MV201,...,P501,P502,PIT501,PIT502,PIT503,FIT601,P601,P602,P603,Normal/Attack
0,0.0,124.3135,1.0,1.0,1.0,251.9226,8.313446,312.7916,0.0,1.0,...,1.0,1.0,9.100231,0.0,3.3485,0.000256,1.0,1.0,1.0,0
1,0.0,124.3920,1.0,1.0,1.0,251.9226,8.313446,312.7916,0.0,1.0,...,1.0,1.0,9.100231,0.0,3.3485,0.000256,1.0,1.0,1.0,0
2,0.0,124.4705,1.0,1.0,1.0,251.9226,8.313446,312.7916,0.0,1.0,...,1.0,1.0,9.100231,0.0,3.3485,0.000256,1.0,1.0,1.0,0
3,0.0,124.6668,1.0,1.0,1.0,251.9226,8.313446,312.7916,0.0,1.0,...,1.0,1.0,9.100231,0.0,3.3485,0.000256,1.0,1.0,1.0,0
4,0.0,124.5098,1.0,1.0,1.0,251.9226,8.313446,312.7916,0.0,1.0,...,1.0,1.0,9.100231,0.0,3.3485,0.000256,1.0,1.0,1.0,0

In [9]:
df[df["Normal/Attack"] == 1].count()

FIT101           0
LIT101           0
 MV101           0
P101             0
P102             0
 AIT201          0
AIT202           0
AIT203           0
FIT201           0
 MV201           0
 P201            0
 P202            0
P203             0
 P204            0
P205             0
P206             0
DPIT301          0
FIT301           0
LIT301           0
MV301            0
MV302            0
 MV303           0
MV304            0
P301             0
P302             0
AIT401           0
AIT402           0
FIT401           0
LIT401           0
P401             0
P402             0
P403             0
P404             0
UV401            0
AIT501           0
AIT502           0
AIT503           0
AIT504           0
FIT501           0
FIT502           0
FIT503           0
FIT504           0
P501             0
P502             0
PIT501           0
PIT502           0
PIT503           0
FIT601           0
P601             0
P602             0
P603             0
Normal/Attack    0
dtype: int64

In [10]:
df_test = pd.read_csv("./Desktop/projects/Source/datasets/SWaT/swat2.csv")

In [12]:
df_test[df_test["Normal/Attack"] == 1].count()

FIT101           54621
LIT101           54621
 MV101           54621
P101             54621
P102             54621
 AIT201          54621
AIT202           54621
AIT203           54621
FIT201           54621
 MV201           54621
 P201            54621
 P202            54621
P203             54621
 P204            54621
P205             54621
P206             54621
DPIT301          54621
FIT301           54621
LIT301           54621
MV301            54621
MV302            54621
 MV303           54621
MV304            54621
P301             54621
P302             54621
AIT401           54621
AIT402           54621
FIT401           54621
LIT401           54621
P401             54621
P402             54621
P403             54621
P404             54621
UV401            54621
AIT501           54621
AIT502           54621
AIT503           54621
AIT504           54621
FIT501           54621
FIT502           54621
FIT503           54621
FIT504           54621
P501             54621
P502             54621
PIT501           54621
PIT502           54621
PIT503           54621
FIT601           54621
P601             54621
P602             54621
P603             54621
Normal/Attack    54621
dtype: int64